package com.jww.rereapp.common.models

data class WebToon(
    val itemList: List<Item>,
    val result: Result
) {
    data class Result(
        val pageNo: Int,
        val resultMessage: String,
        val resultState: String,
        val totalCount: Int,
        val viewItemCnt: Int
    )

    data class Item(
        val ageGradCd: String,
        val ageGradCdNm: String,
        val auspc: Any,
        val bdcpn: Any,
        val cnsleNm: Any,
        val distr: Any,
        val dstrcpIdNm: String,
        val dtaTyCd: Any,
        val dtaTyCdNm: Any,
        val edtn: Any,
        val eventSeCd: Any,
        val eventSeCdNm: Any,
        val fnshYn: String,
        val imageDownloadUrl: String,
        val isbn: String,
        val issn: Any,
        val listSeCd: String,
        val listSeCdNm: String,
        val mainGenreCd: String,
        val mainGenreCdNm: String,
        val makr: Any,
        val mastrId: String,
        val mngt: Any,
        val orginlNationCd: String,
        val orginlNationCdNm: String,
        val orginlTitle: Any,
        val originClCd: Any,
        val originClCdNm: Any,
        val outline: String,
        val pblcateYn: String,
        val pblicteDe: Any,
        val pgeCo: Any,
        val pictrWritrNm: String,
        val plscmpnIdNm: String,
        val pltfomCd: String,
        val pltfomCdNm: String,
        val pltfomCmpnyIdNm: String,
        val prc: Int,
        val prdctNm: String,
        val pusryBeginDe: String,
        val pusryEndDe: String,
        val relDe: Any,
        val setIsbn: String,
        val sntncWritrNm: String,
        val stleClCd: Any,
        val stleClCdNm: Any,
        val stndrd: Any,
        val subtitl: Any,
        val title: String,
        val tlviseBeginDe: Any,
        val tlviseEndDe: Any,
        val webtoonPusryYn: String,
        val wnpzCareer: String,
        val wt: Any
    )
}