name: Environment Variable - Secrets
on: workflow_dispatch

jobs:
  secrets-test:
    runs-on: ubuntu-latest

    ## 깃허브 -> 셋팅 -> Secrets and Variables -> Actions 에 값을 추가한 값이기 떄문에 출력되지 않는다.
    steps:
      - name: Access Secrets
        run: |
          echo "Secret Token: ${{ secrets.TEST_TOKEN }}"